kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-pvc
  namespace: kube-system
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
