---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-efs
  namespace: kube-system
data:
  file.system.id: fs-d5d9729e  # add-filesystem-id
  aws.region: us-east-1    # add region of efs
  provisioner.name: example.com/aws-efs
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-efs
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-efs
    spec:
      containers:
        - name: traefik-efs
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: traefik-efs
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: traefik-efs
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: traefik-efs
                  key: provisioner.name
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      nodeSelector:
        kops.k8s.io/instancegroup: traefik
      volumes:
        - name: pv-volume
          nfs:
            server: fs-d5d9729e.efs.us-east-1.amazonaws.com #EFS ENDPOINT AND PATH TO USE
            path: /
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: aws-efs
  namespace: kube-system
provisioner: example.com/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-efs
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
